baseURL = "http://scanaricladiri.ro"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "Scanari Cladiri"
[Languages.en]
contentDir = "content/english"
copyright = ""
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 2
[[Languages.en.menu.main]]
name = "about"
pre = "#"
url = "about"
weight = 1
[[Languages.en.menu.main]]
name = "portfolio"
pre = "#"
url = "portfolio"
weight = 2
[[Languages.en.menu.main]]
name = "services"
pre = "#"
url = "services"
weight = 3
[[Languages.en.menu.main]]
name = "team"
pre = "#"
url = "team"
weight = 4
[[Languages.en.menu.main]]
name = "blog"
pre = "#"
url = "blog"
weight = 5
[[Languages.en.menu.main]]
name = "contact"
pre = "#"
url = "contact"
weight = 6
[Languages.ro]
contentDir = "content/romanian"
copyright = ""
home = "Acasa"
languageCode = "ro-ro"
languageName = "Ro"
weight = 1
[[Languages.ro.menu.main]]
name = "Despre noi"
pre = "#"
url = "about"
weight = 1
[[Languages.ro.menu.main]]
name = "Portofoliu"
pre = "#"
url = "portfolio"
weight = 2
[[Languages.ro.menu.main]]
name = "Servicii"
pre = "#"
url = "services"
weight = 3
[[Languages.ro.menu.main]]
name = "Echipa"
pre = "#"
url = "team"
weight = 4
[[Languages.ro.menu.main]]
name = "Blog"
pre = "#"
url = "blog"
weight = 5
[[Languages.ro.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 6
[params]
author = ""
description = ""
google_analytics_id = ""
logo = "images/logo-2.png"
post_share = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = "images/logo-2.png"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/Scan%C4%83ri-Cl%C4%83diri-3D-Building-Laser-Scanning-615829785223361/?eid=ARBer6rLCzjy6Kr9qodmnWEL9ZLnQ-EfsfavbRR9_coNwNAfEai1IaceD0UgBYOuRaSMhRciEKUO7MD0"
[[params.social]]
icon = "ti-youtube"
link = "https://www.youtube.com/channel/UCB8B_1Vc4PsDycCtEDF_tzw"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/scanaricladiri/"
[[params.social]]
icon = "ti-pinterest"
link = "#"
